#!/bin/bash

if [[ "$#" -ne 2 ]]; then
    echo "invalid number of arguments"
    exit 1
fi


#curl -s 'https://leetcode.com/graphql/' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0' -H 'Accept: */*' -H 'Accept-Language: en-US' --compressed -H 'Referer: https://leetcode.com/graphql/' -H 'content-type: application/json' -H 'x-csrftoken: m39NyKMP4W3ZqdC4gHPjs7JsIWSOtArGZtYldErDksi9YxmFQGwhEjQZdtmrfqWI' -H 'authorization: ' -H 'Origin: https://leetcode.com' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Cookie: NEW_PROBLEMLIST_PAGE=1; csrftoken=m39NyKMP4W3ZqdC4gHPjs7JsIWSOtArGZtYldErDksi9YxmFQGwhEjQZdtmrfqWI' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'TE: trailers' --data-raw '{"query":"\n    query problemsetQuestionList($categorySlug: String, $limit: Int, $skip: Int, $filters: QuestionListFilterInput) {\n  problemsetQuestionList: questionList(\n    categorySlug: $categorySlug\n    limit: $limit\n    skip: $skip\n    filters: $filters\n  ) {\n    total: totalNum\n    questions: data {\n      acRate\n      difficulty\n      freqBar\n      frontendQuestionId: questionFrontendId\n      isFavor\n      paidOnly: isPaidOnly\n      status\n      title\n      titleSlug\n      topicTags {\n        name\n        id\n        slug\n      }\n      hasSolution\n      hasVideoSolution\n    }\n  }\n}\n    ","variables":{"categorySlug":"","skip":'$1',"limit":'$2',"filters":{}},"operationName":"problemsetQuestionList"}'
curl -s 'https://leetcode.com/graphql/' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0' -H 'Accept: */*' -H 'Accept-Language: en-US' --compressed -H 'Referer: https://leetcode.com/graphql/' -H 'content-type: application/json' -H 'authorization: ' -H 'Origin: https://leetcode.com' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'TE: trailers' --data-raw '{"query":"\n    query problemsetQuestionList($categorySlug: String, $limit: Int, $skip: Int, $filters: QuestionListFilterInput) {\n  problemsetQuestionList: questionList(\n    categorySlug: $categorySlug\n    limit: $limit\n    skip: $skip\n    filters: $filters\n  ) {\n    total: totalNum\n    questions: data {\n      acRate\n      difficulty\n      frontendQuestionId: questionFrontendId\n      paidOnly: isPaidOnly\n     title\n      titleSlug\n    }\n  }\n}\n    ","variables":{"categorySlug":"","skip":'$1',"limit":'$2',"filters":{}},"operationName":"problemsetQuestionList"}'

